export const ignoreFolders = [
  'node_modules',
  'cdk.out',
  'dist',
  'coverage',
  'test',
  'tests',
  'tests-e2e',
  'tests-unit',
  'tests-integration',
  'tests-acceptance',
  'tests-functional',
  'tests-regression',
  'tests-performance',
  'tests-security',
  'tes',
  '.git',
  'public',
  'dist-electron',
  'release',
  'postgres',
]
export const ignoreFiles = ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']
export const ignorePatterns = [
  /\.env.*/,
  /\.ico/,
  /\.png/,
  /\.webp/,
  /\.jpg/,
  /\.jpeg/,
  /\.svg/,
  /\.gif/,
  /\.eot/,
  /\.otf/,
]
